<a href="https://colab.research.google.com/github/Anikate-De/TensorFlow-Deep-Learning/blob/main/Introduction_to_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Basics

Table of Contents - 


*   Creating & Manipulating Tensors
*   Tensorflow + Numpy
*   Expanding Tensors
*   Matrix Multiplication
*   One Hot Encoding


#### Creating and Manipulating Tensors

In [1]:
import tensorflow as tf
tf.__version__

'2.11.0'

In [2]:
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [3]:
vector = tf.constant([10,20,30])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [4]:
vector.ndim

1

In [5]:
matrix = tf.constant([[5,32,5],[14,21,7],[7,2,5]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 32,  5],
       [14, 21,  7],
       [ 7,  2,  5]], dtype=int32)>

In [6]:
matrix.ndim

2

Mutable Tensors

In [7]:
m_tensor = tf.Variable([12,23,2352,23])
m_tensor

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([  12,   23, 2352,   23], dtype=int32)>

In [8]:
m_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [9]:
m_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([   9,   23, 2352,   23], dtype=int32)>

Random Tensors

In [10]:
gen = tf.random.Generator.from_seed(4)
gen.uniform(shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.48252344, 0.15580535],
       [0.3703227 , 0.49210668],
       [0.567016  , 0.2077086 ]], dtype=float32)>

In [11]:
gen = tf.random.Generator.from_seed(4)
gen.normal(shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ],
       [ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114]], dtype=float32)>

In [12]:
gen_nd = tf.random.Generator.from_non_deterministic_state()
gen_nd.uniform(shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.00311267, 0.61933935],
       [0.8690939 , 0.8582345 ],
       [0.6896846 , 0.56162727]], dtype=float32)>

In [13]:
gen_2 = tf.random.Generator.from_seed(4)
tf.random.shuffle(gen_2.normal(shape = (3,2)))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114],
       [ 1.0019137 ,  0.6735137 ]], dtype=float32)>

In [14]:
tensor = tf.constant([[10,2,3],[13,14,5],[46,36,1]])

tf.random.set_seed(4)
shuffled = tf.random.shuffle(tensor, seed =4)

tensor, shuffled

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10,  2,  3],
        [13, 14,  5],
        [46, 36,  1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10,  2,  3],
        [13, 14,  5],
        [46, 36,  1]], dtype=int32)>)

#### Tensorflow + Numpy

In [15]:
tf.zeros((3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [16]:
tf.ones((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [17]:
import numpy as np
np_A = np.array([2,3,1])
np_A

array([2, 3, 1])

In [18]:
tf_A = tf.constant(np_A)
tf_A

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 3, 1])>

**NOTE:** The default dataathpe of NumPy arrays is float64 while that of TensorFlow is float32

#### Expanding Tensors

In [19]:
rank_2_tensor = tf.zeros(shape=(2,3))
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

Alternative to `tf.newaxis`
Works just like inserting an element to a list, here the list is `tensor.shape`

In [21]:
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

#### Matrix multiplication

In [22]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [23]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [24]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [25]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

Multiplying matrices of different dimensions.

In [26]:
tensor = tf.constant([[1,2],[3,4],[5,6]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [27]:
# This should give an error
tensor @ tensor

InvalidArgumentError: ignored

In [28]:
tf.reshape(tensor, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [29]:
tensor @ tf.reshape(tensor, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [30]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [31]:
tensor @ tf.transpose(tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [32]:
tf.matmul(tensor, tensor, transpose_b=True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [33]:
# Using tensordot()
tf.tensordot(tensor, tf.transpose(tensor), axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

#### One-Hot Encoding

In [43]:
indices = [2,1,2]
tf.one_hot(indices, depth = 3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [44]:
indices = [0,1,2,3,4]
tf.one_hot(indices, depth = 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [46]:
tf.one_hot(indices, depth = 3)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [47]:
tf.one_hot(indices, depth = 8)

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>