<a href="https://colab.research.google.com/github/Anikate-De/TensorFlow-Deep-Learning/blob/main/Introduction_to_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Basics

Table of Contents - 


*   Creating & Manipulating Tensors
*   Tensorflow + Numpy
*   Expanding Tensors
*   Matrix Multiplication
*   One Hot Encoding


#### Creating and Manipulating Tensors

In [1]:
import tensorflow as tf
tf.__version__

'2.11.0'

In [2]:
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [3]:
vector = tf.constant([10,20,30])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [4]:
vector.ndim

1

In [5]:
matrix = tf.constant([[5,32,5],[14,21,7],[7,2,5]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 32,  5],
       [14, 21,  7],
       [ 7,  2,  5]], dtype=int32)>

In [6]:
matrix.ndim

2

Mutable Tensors

In [7]:
m_tensor = tf.Variable([12,23,2352,23])
m_tensor

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([  12,   23, 2352,   23], dtype=int32)>

In [8]:
m_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [9]:
m_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([   9,   23, 2352,   23], dtype=int32)>

Random Tensors

In [10]:
gen = tf.random.Generator.from_seed(4)
gen.uniform(shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.48252344, 0.15580535],
       [0.3703227 , 0.49210668],
       [0.567016  , 0.2077086 ]], dtype=float32)>

In [11]:
gen = tf.random.Generator.from_seed(4)
gen.normal(shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ],
       [ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114]], dtype=float32)>

In [12]:
gen_nd = tf.random.Generator.from_non_deterministic_state()
gen_nd.uniform(shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.08305824, 0.61589456],
       [0.6534134 , 0.4597801 ],
       [0.98435974, 0.2061199 ]], dtype=float32)>

In [13]:
gen_2 = tf.random.Generator.from_seed(4)
tf.random.shuffle(gen_2.normal(shape = (3,2)))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ],
       [ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114]], dtype=float32)>

In [14]:
tensor = tf.constant([[10,2,3],[13,14,5],[46,36,1]])

tf.random.set_seed(4)
shuffled = tf.random.shuffle(tensor, seed =4)

tensor, shuffled

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10,  2,  3],
        [13, 14,  5],
        [46, 36,  1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10,  2,  3],
        [13, 14,  5],
        [46, 36,  1]], dtype=int32)>)

#### Tensorflow + Numpy

In [15]:
tf.zeros((3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [16]:
tf.ones((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [17]:
import numpy as np
np_A = np.array([2,3,1])
np_A

array([2, 3, 1])

In [18]:
tf_A = tf.constant(np_A)
tf_A

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 3, 1])>

**NOTE:** The default dataathpe of NumPy arrays is float64 while that of TensorFlow is float32

#### Expanding Tensors

In [19]:
rank_2_tensor = tf.zeros(shape=(2,3))
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

Alternative to `tf.newaxis`
Works just like inserting an element to a list, here the list is `tensor.shape`

In [21]:
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

#### Matrix multiplication

In [22]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [23]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [24]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [25]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

Multiplying matrices of different dimensions.

In [26]:
tensor = tf.constant([[1,2],[3,4],[5,6]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [27]:
# This should give an error
tensor @ tensor

InvalidArgumentError: ignored

In [28]:
tf.reshape(tensor, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [29]:
tensor @ tf.reshape(tensor, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [30]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [31]:
tensor @ tf.transpose(tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [32]:
tf.matmul(tensor, tensor, transpose_b=True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [33]:
# Using tensordot()
tf.tensordot(tensor, tf.transpose(tensor), axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

#### One-Hot Encoding

In [34]:
indices = [2,1,2]
tf.one_hot(indices, depth = 3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [35]:
indices = [0,1,2,3,4]
tf.one_hot(indices, depth = 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [36]:
tf.one_hot(indices, depth = 3)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [37]:
tf.one_hot(indices, depth = 8)

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>

# Exercises



1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6.
8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.


In [41]:
# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()
vector = tf.constant([10,9,8])
scalar = tf.constant(4)
matrix = tf.constant([[10,9],[8,7],[6,5]])
tensor = tf.constant([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(scalar, vector, matrix, tensor, sep='\n')

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([10  9  8], shape=(3,), dtype=int32)
tf.Tensor(
[[10  9]
 [ 8  7]
 [ 6  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]], shape=(2, 3, 2), dtype=int32)


In [43]:
# Find the shape, rank and size of the tensors you created in 1.
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [44]:
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([3]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [45]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([3, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [46]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 3, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [52]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300]
generator = tf.random.Generator.from_seed(4)
A = generator.uniform(shape = [5,300], maxval = 1)
B = generator.uniform(shape = [5,300], maxval = 1)
A, B

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.48252344, 0.15580535, 0.3703227 , ..., 0.6030959 , 0.5261806 ,
         0.29263592],
        [0.36828172, 0.9125351 , 0.9311757 , ..., 0.28039837, 0.23856235,
         0.0295794 ],
        [0.49198222, 0.6657673 , 0.8861321 , ..., 0.9389367 , 0.6189861 ,
         0.09308314],
        [0.67127347, 0.554566  , 0.41143024, ..., 0.9333025 , 0.5141679 ,
         0.6085166 ],
        [0.9822712 , 0.155164  , 0.21270347, ..., 0.54543686, 0.32094967,
         0.6671035 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.98478794, 0.59075475, 0.94479775, ..., 0.5115601 , 0.19735217,
         0.38531756],
        [0.5596421 , 0.81612885, 0.04916477, ..., 0.41156566, 0.97969055,
         0.2477696 ],
        [0.478989  , 0.29646766, 0.6018213 , ..., 0.46831   , 0.8992487 ,
         0.7710763 ],
        [0.7299831 , 0.569106  , 0.7414402 , ..., 0.8913442 , 0.9727906 ,
         0.0993737 ],
        [0.92722

In [57]:
# Multiply the two tensors you created in 3 using matrix multiplication
A_BT = tf.matmul(A, B, transpose_b = True)
AT_B = tf.matmul(A, B, transpose_a = True)
A_BT, AT_B

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[75.55132 , 74.365746, 76.039635, 76.38896 , 73.098564],
        [78.32044 , 74.37536 , 74.61407 , 76.59617 , 73.49047 ],
        [74.78546 , 73.561714, 71.09874 , 75.65093 , 72.07529 ],
        [71.47365 , 68.48248 , 68.918884, 72.4144  , 68.58531 ],
        [77.21607 , 73.47504 , 74.361496, 74.025116, 73.40432 ]],
       dtype=float32)>, <tf.Tensor: shape=(300, 300), dtype=float32, numpy=
 array([[2.3177464 , 1.4256486 , 1.5359371 , ..., 1.7660168 , 1.5569967 ,
         1.3512692 ],
        [1.531719  , 1.3990825 , 1.0462776 , ..., 1.3464888 , 2.0637934 ,
         0.9538065 ],
        [1.8078227 , 1.5431794 , 1.2920709 , ..., 1.4710809 , 2.1836374 ,
         1.2335654 ],
        ...,
        [2.3876214 , 1.567965  , 1.9895476 , ..., 1.9947534 , 2.1490502 ,
         1.4673301 ],
        [1.6210994 , 1.0836586 , 1.3502225 , ..., 1.2916064 , 1.396172  ,
         0.99544036],
        [1.4120848 , 0.7829163 , 0.9672459 , ..., 1.1138

In [58]:
# Multiply the two tensors you created in 3 using dot product.
tf.tensordot(A, tf.transpose(B), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.55133 , 74.365746, 76.03965 , 76.38897 , 73.09859 ],
       [78.32044 , 74.37536 , 74.61405 , 76.59618 , 73.49047 ],
       [74.78547 , 73.5617  , 71.09874 , 75.65094 , 72.07527 ],
       [71.47365 , 68.48249 , 68.918884, 72.414406, 68.58531 ],
       [77.21606 , 73.47503 , 74.36149 , 74.025116, 73.40433 ]],
      dtype=float32)>

In [60]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
R = generator.uniform(shape = [224, 224, 3], maxval = 1)
R

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.06055391, 0.20765138, 0.39415145],
        [0.88959014, 0.58133674, 0.7304603 ],
        [0.4234984 , 0.70738983, 0.69285405],
        ...,
        [0.13194835, 0.9543567 , 0.36554527],
        [0.46473908, 0.37070096, 0.20172966],
        [0.9464748 , 0.41708136, 0.47961164]],

       [[0.46503544, 0.13552952, 0.6256918 ],
        [0.70894873, 0.79171   , 0.29167414],
        [0.3747114 , 0.59163976, 0.27431762],
        ...,
        [0.8800162 , 0.9663782 , 0.6629566 ],
        [0.65770805, 0.8434397 , 0.14218843],
        [0.6889287 , 0.8501986 , 0.92880225]],

       [[0.02502942, 0.4491155 , 0.9136689 ],
        [0.47701693, 0.83316267, 0.18190026],
        [0.9994818 , 0.4328984 , 0.8799443 ],
        ...,
        [0.8437983 , 0.8072525 , 0.9813819 ],
        [0.51142156, 0.6302892 , 0.20099247],
        [0.678445  , 0.20886219, 0.13179481]],

       ...,

       [[0.24661326, 0.07503164, 0.21540868],
        [0.21

In [63]:
# Find the min and max values of the tensor you created in 6.
tf.reduce_min(R).numpy(), tf.reduce_max(R).numpy()

(2.861023e-06, 0.9999894)

In [66]:
# Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
X_expanded = generator.uniform(maxval = 1, shape = [1, 224, 224, 3])
X = tf.squeeze(X_expanded)
X_expanded, X

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[0.08117831, 0.81527174, 0.28746533],
          [0.8846065 , 0.96122515, 0.5228605 ],
          [0.7206248 , 0.16867936, 0.71110976],
          ...,
          [0.53833485, 0.02839375, 0.6602771 ],
          [0.05669451, 0.9795083 , 0.12071812],
          [0.10473025, 0.3303094 , 0.55010843]],
 
         [[0.02941966, 0.7347597 , 0.2454226 ],
          [0.26676595, 0.11856067, 0.6541959 ],
          [0.32202137, 0.25296986, 0.44977129],
          ...,
          [0.7455926 , 0.47627652, 0.31705928],
          [0.61813235, 0.9563526 , 0.5575528 ],
          [0.93498456, 0.1042856 , 0.34267318]],
 
         [[0.2934518 , 0.21182227, 0.5480555 ],
          [0.9061264 , 0.14498758, 0.77594376],
          [0.13320243, 0.3665793 , 0.06977117],
          ...,
          [0.8568398 , 0.15003228, 0.15453744],
          [0.8903086 , 0.48498988, 0.20910311],
          [0.4701903 , 0.27314508, 0.68726397]],
 
         ...,
 
       

In [68]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

tensor = tf.constant([1,23,41,21,5,12,15,25,346,0])

tf.argmax(tensor).numpy()

8

In [69]:
# One-hot encode the tensor you created in 9.
tf.one_hot(tensor, depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Extra Curriculum

Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).

How would you calculate your grocery bill for the month and for the year using tensors?

In [72]:
'''
First, we create a tensor to store all the input data

The input data is structured in the following way -

[[cost_of_item, no_of_items_bought],
 [100, 3]]
'''

bill = tf.constant([[9.99, 4],
                    [13.50, 1],
                    [49.99, 1],
                    [0.87, 6],
                    [4.99, 1],
                    [3.25, 3],
                    [2.00, 1],
                    [18.99, 4],
                    [7.00, 2],
                    [0.50, 2],
                    [8.50, 3]])

bill

<tf.Tensor: shape=(11, 2), dtype=float32, numpy=
array([[ 9.99,  4.  ],
       [13.5 ,  1.  ],
       [49.99,  1.  ],
       [ 0.87,  6.  ],
       [ 4.99,  1.  ],
       [ 3.25,  3.  ],
       [ 2.  ,  1.  ],
       [18.99,  4.  ],
       [ 7.  ,  2.  ],
       [ 0.5 ,  2.  ],
       [ 8.5 ,  3.  ]], dtype=float32)>

In [76]:
'''
We then extract the cost prices of items, and the corressponding number of items purchased into two separate tensors

So now, cost of items will be present in a vector (a list)
Same applies to the number of items purchased
'''

prices = bill[:, 0]
# Squeeze Prices to get rid of empty dimension
prices = tf.squeeze(prices)

items = bill[:, -1]
# Squeeze Prices to get rid of empty dimension
items = tf.squeeze(items)

prices, items

(<tf.Tensor: shape=(11,), dtype=float32, numpy=
 array([ 9.99, 13.5 , 49.99,  0.87,  4.99,  3.25,  2.  , 18.99,  7.  ,
         0.5 ,  8.5 ], dtype=float32)>,
 <tf.Tensor: shape=(11,), dtype=float32, numpy=array([4., 1., 1., 6., 1., 3., 1., 4., 2., 2., 3.], dtype=float32)>)

In [77]:
'''
We now multiply the two tensors prices & items together using element-wise multiplication
'''

expenses = prices * items

expenses

<tf.Tensor: shape=(11,), dtype=float32, numpy=
array([39.96     , 13.5      , 49.99     ,  5.2200003,  4.99     ,
        9.75     ,  2.       , 75.96     , 14.       ,  1.       ,
       25.5      ], dtype=float32)>

In [79]:
'''
We finally get the sum of all the values present in the expenses tensor
'''

total_expense = tf.reduce_sum(expenses)

total_expense.numpy()

241.87

In [81]:
# Print the value in a fancier way

print('The total expense from the monthly grocery bill input is,', total_expense.numpy())

# Get the ceiling value of the expense

from math import ceil
print('The total payable is,', ceil(total_expense.numpy()))

The total expense from the monthly grocery bill input is, 241.87
The total payable is, 242


In [83]:
'''
The expense incurred for the year is 12 times the expense in the month
'''

print('The yearly expense from this particular monthly bill is,', ceil(total_expense.numpy() * 12))

The yearly expense from this particular monthly bill is, 2903
